services:
  - type: web
    name: house-price-prediction-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
  - type: web
    name: house-price-prediction-frontend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app/frontend.py --server.port $PORT --server.address 0.0.0.0
